import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/**/**/*.{js,ts,jsx,tsx,mdx}',
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      xxxl: { 'max': '3019px' },
      xxl: { 'max': '2560px' },
      xl: { 'max': '1920px' },
      'desktop-l': { 'max': '1880px' },
      'desktop-m': { 'max': '1680px' },
      'laptop-x': { 'max': '1440px' },
      'laptop-m': { 'max': '1280px' },
      lg: { 'max': '1170px' },
      md: { 'max': '991px' },
      sm: { 'max': '767px' },
      xs: { 'max': '414px' },
      xxs: { 'max': '375px' },
      '2xl': '1921px',
      DEFAULT: '1576px'
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '26px',
        xxl: '3rem',
        xl: '3rem',
        lg: '3rem',
        md: '30px',
        sm: '18px',
        'xs': '15px',
      },
    },
    fontFamily: {
      primary: ['Urbanist', 'sans-serif'],
      secondary: ['Inter', 'sans-serif'],
      accent: ['Urbanist', 'sans-serif']
    },
    fontSize: {
      'modal-heading': '454px',
      'modal-heading-2': '238px',
      'modal-heading-3': '195px',
      'modal-heading-4': '180px',
      'primary-heading': '168px',
      'primary-heading-2': '150px',
      'primary-heading-3': '134px',
      'primary-heading-4': '131px',
      'primary-heading-5': '104px',
      'primary-heading-6': '100px',
       'secondary-heading': '95px',
       'secondary-heading-2': '94px',
       'secondary-heading-3': '90px',
       'threeth-heading': '87px',
       'threeth-heading-2': '85px',
       'threeth-heading-3': '82px',
       'threeth-heading-4': '80px',
       'fourth-heading': '70px',
       'fiveth-heading': '68px',
       'fiveth-heading-2': '67px',
       'fiveth-heading-3': '65px',
       'fiveth-heading-4': '64px',
       'sixth-heading': '58px',
       'sixth-heading-2': '55px',
       'sixth-heading-3': '53px',
      'text-xxl-large': '44px',
      'text-extra-large': '42px',
      'text--large': '40px',
      'body-text': '24px',
      'body-text-2': '23px',
      'body-text-3': '22px',
      'body-text-4': '21px',
      'body-text-5': '20px',
      'body-text-6': '18px',
 
      'text-accend': '36px',
      'text-accend-1': '35px',
      'text-accend-2': '33px',
      'text-accend-3': '32px',
      'text-accend-4': '31px',
      'text-accend-5': '30px',

      'text-medium': '29px',
      'text-medium-2': '28px',
      'text-medium-3': '26px',
      'text-medium-4': '25px',

      'text-small': '16px',
      'text-xs-small': '15px',
      'text-xxs-small': '14px',
      'text-extra-small': '12px',
      
      'base': '1rem',
      'xl': '1.25rem',
      '2xl': '1.563rem',
      '3xl': '1.953rem',
      '4xl': '2.441rem',
      '5xl': '3.052rem',
    },
    extend: {
      colors: {
        'primary': '#F2EFEF',
        'secondary': 'rgba(0, 175, 252, 0.78)',
        'secondary-2': '#2997FF',
        'accent-color': '#212529',
        'modal-text-color': 'rgba(116, 116, 116, 0.28)',
        'modal-text-color-2': '#363636',
        'modal-text-color-4': '#7B7B7B21',
        'modal-text-color-3': '#383838',
        'gold-color': '#a79a66',
        'gold-light': '#bdae72',
        'neu-btn-color': '#377AFF',
        'neu-btn-hover-color': '#2563EB',
        'neu-blue':  '#2997FF',
        'neu-light-blue':  'rgba(0, 175, 252, 0.78)',
        'neu-black': '#000000',
        'neu-black-2': '#1C1919',
        'neu-black-3': '#161617',
        'neu-gray-black': '#424242',
        'neu-gray-black-2': '#1C1C1C',
        'neu-tertarry-color': '#0A0A0A',
        'neu-gray': '#C4C4C4',
        'neu-white': '#ffffff',
        'title': '#1B1B1D',
        'tab-para': '#333333',
        'gray': '#A0A0A0',
        'gray-light': '#D9D9D9',
        'gray-light-2': '#F2EFEF',
        'light-gray': '#F4F4F4',
        'dark-gray': '#A6A6AB',
        'gray-extra-light': '#E5E5E5',
        'slate': '#9b9b9b',
        'meta': '#414141',
        'body': '#191919',
        'body-light': '#0f0f0f',
        'sky': '#012A5E',
        'box-shadow-primary':  '0px 4px 25px 0px rgba(45, 44, 44, 0.25)',
        'text-shadow-primary':  '0px 4px 4px rgba(0, 0, 0, 0.25)',
        'opcity-color-1': 'rgba(255, 255, 255, 0.28)',
      },
      backgroundImage: {
        'inner-cta':
          "linear-gradient(96.34deg,#926AFF 0%,#FF77B0 50%,#FFB367 100%)",
      },
      gridTemplateColumns: {
        // Simple 16 column grid
        '16': 'repeat(16, minmax(0, 1fr))',
      },
      gridColumn: {
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
        'span-15': 'span 15 / span 15',
        'span-16': 'span 16 / span 16',
      }
    },
  },
  plugins: [],
}
export default config
