import type { Metadata } from 'next';
import './globals.css'
import { Urbanist, Inter } from 'next/font/google';
import { Footer, Navbar } from '@/components';
import StickyNavbar from '@/components/navbar/sticky-navbar';
import React from "react";
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})
 
const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  display: 'swap',
})
export const metadata: Metadata = {
  title: 'Particular Merketing Agency Website',
  description: 'Generated by Particular Merketing Agency',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang="en" className={`${inter.variable} ${urbanist.variable}`}>

			<body className="pca-marketing-page-body md:border-0">
				<Navbar />
				<StickyNavbar />
				<main className="pca-marketing-main-wraper">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
